site_name: Kelon Docs
theme: material


repo_name: foundato/kelon
repo_url: https://github.com/foundato/kelon

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

pages:
  - "Introduction": "index.md"
  - "Kelon":
    - "In a nutshell": "kelon/In-A-Nutshell.md"
    - "Configuration": "kelon/Configuration.md"
    - "Introduction": "kelon/Introduction.md"
    - "Architecture":
      - "Components": "kelon/architecture/Components.md"
      - "Request mapping": "kelon/architecture/Request-Mapping.md"
      - "Query AST": "kelon/architecture/Query-AST.md"
  - "How-To's":
    - "Local deployment": "how-to/Local-Deployment.md"
    - "Run the example": "how-to/Run-The-Example.md"
    - "Appstore example": "how-to/Appstore-Example.md"